debug = false

[filter_settings]
raw_image_winsorizing_percentile = 99.0
quant_image_winsorizing_percentile = 99.0
gaussian_filter = true

[processing_settings]
pos_mode = true
ppm = 10.0
bin_size = 5.0
m2_isotope_correction = true
na_isotope_correction = true
online_calibration = true
pos_calibrant = 798.541
neg_calibrant = 798.541
calibration_ppm = 30.0
calibration_min_intensity = 10000

[selection_settings]
minimum_pixels = 300
minimum_intensity = 500

[database_settings]
last_used_database = "MSI_database_V1.0"

[save_settings]
save_raw_images = true
save_iso_images = true
save_quant_images = true
save_individual_unfiltered = false
save_individual_filtered_scaled = true
save_panel_filtered_scaled = false
