debug = false

[filter_settings]
raw_image_winsorizing_percentile = 95.0
quant_image_winsorizing_percentile = 99.0
gaussian_filter = true

[processing_settings]
pos_mode = true
ppm = 10.0
bin_size = 5.0
db_isotope_correction = true
na_isotope_correction = true
online_calibration = true
pos_calibrant = 798.541
neg_calibrant = 885.5499
calibration_ppm = 30.0
calibration_min_intensity = 10000
imputation = true

[selection_settings]
selection_method = "feature"
minimum_pixels = 300
minimum_intensity = 500
feature_noise_sigma = 4.0
feature_minimum_pixels = 10

[database_settings]
last_used_database = "MSI_database_V1.0"

[save_settings]
save_raw_images = true
save_iso_images = true
save_quant_images = true
save_individual_unfiltered = false
save_individual_filtered_scaled = true
save_panel_filtered_scaled = false

[scalebar_settings]
enabled = true
auto = true
manual_length_um = 100

[sprayer_settings]
x_left = 22
x_right = 40
y_bottom = 5
y_top = 17
margin = 5
total_used_volume_mL = 0.8
syringe_flow_mL_per_min = 0.06
drying_time_min = 0.5
drying_cycles = 16
initial_equilibration_min = 0.833
stock_conc_mg_per_mL = 0.11
working_dilution_factor = 3.0
volume_working_stock_uL = 1000.0
final_mix_volume_mL = 8.0
molecular_weight_ug_per_umol = 504.69
