"""Compatibility facade for MSI data models, importers, and image processing.

The implementation is split across focused modules. Existing callers can keep
importing from ``app.dataprocess`` while new code should prefer the narrower
modules directly.
"""

from app.image_processing import (
    _add_padding,
    _apply_transparent_mask,
    _sum_images_for_neutral,
    db_isotope_correction,
    na_isotope_correction,
    ppm_to_tolerance,
    quantitaton,
    replace_nan_with_median,
    sum_adducts,
    threshold_check,
    winsorize_image,
)
from app.importers.anndata import (
    _build_anndata_average_spectrum,
    _build_anndata_grid,
    _build_anndata_raw_images,
    _build_transparent_mask,
    _close_anndata,
    _coerce_spot_size,
    _filter_database_for_matched_adducts,
    _get_anndata_foreground,
    _get_anndata_mz_modes,
    _get_anndata_mzs,
    _get_anndata_sample_labels,
    _get_anndata_spatial,
    _match_anndata_features_to_database,
    _matrix_to_numpy,
    _normalize_anndata_ion_mode,
    _normalize_bool,
    _read_anndata,
    _select_anndata_matrix,
    _spot_size_for_sample,
    get_anndata_matrix_choices,
    load_database_anndata_collection,
)
from app.importers.common import _combine_mode_databases
from app.importers.imzml import (
    _normalize_selections,
    detect_imzml_ion_mode,
    load_database_image_collection,
)
from app.msi_data import (
    AnnDataMatrixChoice,
    ImageType,
    LoadedMsiData,
    SampleCollection,
    SampleFiles,
    SampleIonMode,
    SectionMsiImage,
    _combine_section_images,
    _merge_average_spectra,
    _polarity_to_ion_mode,
    _unique_label,
)

__all__ = [
    "AnnDataMatrixChoice",
    "ImageType",
    "LoadedMsiData",
    "SampleCollection",
    "SampleFiles",
    "SampleIonMode",
    "SectionMsiImage",
    "_add_padding",
    "_apply_transparent_mask",
    "_build_anndata_average_spectrum",
    "_build_anndata_grid",
    "_build_anndata_raw_images",
    "_build_transparent_mask",
    "_close_anndata",
    "_coerce_spot_size",
    "_combine_mode_databases",
    "_combine_section_images",
    "_filter_database_for_matched_adducts",
    "_get_anndata_foreground",
    "_get_anndata_mz_modes",
    "_get_anndata_mzs",
    "_get_anndata_sample_labels",
    "_get_anndata_spatial",
    "_match_anndata_features_to_database",
    "_matrix_to_numpy",
    "_merge_average_spectra",
    "_normalize_anndata_ion_mode",
    "_normalize_bool",
    "_normalize_selections",
    "_polarity_to_ion_mode",
    "_read_anndata",
    "_select_anndata_matrix",
    "_spot_size_for_sample",
    "_sum_images_for_neutral",
    "_unique_label",
    "db_isotope_correction",
    "detect_imzml_ion_mode",
    "get_anndata_matrix_choices",
    "load_database_anndata_collection",
    "load_database_image_collection",
    "na_isotope_correction",
    "ppm_to_tolerance",
    "quantitaton",
    "replace_nan_with_median",
    "sum_adducts",
    "threshold_check",
    "winsorize_image",
]
